version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: top-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/top_project_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - top-network

  frontend:
    build:
      context: ./frontend
    container_name: top-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - top-network

networks:
  top-network:
