spring:
  datasource:
    url: jdbc:mysql://localhost:3306/top_project_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: topuser
    password: topuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinwook5062@gmail.com
    password: wgebgfosnlfoqmsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
